### ISSUE TITLE
Set Algolia prefix

### ISSUE THREAD

**Issue by lkesteloot** [Progress-Studies-Forum/ForumMagnum#15]
The indexes in Algolia have names like "nullposts" and "nullusers". These names come from the code in `packages/lesswrong/lib/algoliaUtil.ts`, which concatenates the `ALGOLIA_PREFIX` with strings like `"users"`. The prefix comes from the public database setting `algolia.indexPrefix`. I don't know what the other forums use here, but presumably anything is fine since it's our own Algolia instance. So maybe `pf-` to keep it short?

**Comment by sentalis** [comment]
Added the `pf-` prefix.
