### ISSUE TITLE
Fix Algolia search

### ISSUE THREAD

**Issue by lkesteloot** [Progress-Studies-Forum/ForumMagnum#16]
This is a catch-all bug for problems noticed with Algolia search. We can split these off once we understand the problems better.

- Each paragraph of each post ends up as a separate Algolia record. When searching, a post will show up multiple times, once for each paragraph that matches the search term.
- When searching from the search bar, the first letter submits a search just for posts, and a search for all indexes (posts, users, tags, and comments). Subsequent letters submit only for all four, not for just posts. I don't know why we have an extra request for just posts.
- Any request that includes the tags index fails completely because we don't have such an index. This is why subsequent letters don't update the search results, and why the result page is empty. I don't know if we need to manually create the tags index or if it will be automatically created when we create our first tag.

**Comment by lkesteloot** [comment]
There's a function called `algoliaConfigureIndexes()` (in `algoliaConfigureIndexes.ts`) that configures the Algolia indexes. It's not called from anywhere, but it's put in an object called `Vulcan`, which is accessible to the Meteor shell (whatever that is). So I think we should run this shell and run `Vulcan.algoliaConfigureIndexes()` to set up our indexes properly. This might help with the tags index problem mentioned above.

**Comment by sentalis** [comment]
> There's a function called algoliaConfigureIndexes() (in algoliaConfigureIndexes.ts) that configures the Algolia indexes. It's not called from anywhere, but it's put in an object called Vulcan, which is accessible to the Meteor shell (whatever that is). So I think we should run this shell and run Vulcan.algoliaConfigureIndexes() to set up our indexes properly. This might help with the tags index problem mentioned above.

I've executed this on the development (`pf-*`) indexes. The code from `packages/lesswrong/server/scripts/algoliaConfigureIndexes.ts` is bound to the `Vulcan` global. The Meteor shell isn't used, it's instead `yarn shell`. This will call into `packages/lesswrong/server/serverStartup.ts::serverStartup`, which will then call `initShell` and `watchForShellCommands` from the same file.

It's the latter which will read from `./tmp/pendingShellCommands` and execute (through `eval`) in the environment context the code in that file.

> - Each paragraph of each post ends up as a separate Algolia record. When searching, a post will show up multiple times, once for each paragraph that matches the search term.
> - Any request that includes the tags index fails completely because we don't have such an index. This is why subsequent letters don't update the search results, and why the result page is empty. I don't know if we need to manually create the tags index or if it will be automatically created when we create our first tag.

Both of these now seem to be fixed.
