### ISSUE TITLE
Remove 'Shortform' from side nav

### ISSUE THREAD

**Issue by akuataya** [Progress-Studies-Forum/ForumMagnum#25]
They'll be under All Posts.

<img width="1440" alt="Screen Shot 2022-02-20 at 9 48 29 AM" src="https://user-images.githubusercontent.com/11878478/154856527-6f259123-832a-49f6-947a-16fc419ee3fc.png">

**Comment by akuataya** [comment]
Overlap with #29.

**Comment by sentalis** [comment]
Closed in 48ee7348f5a7461684e7fc58f64e08248b920c6e.
