### ISSUE TITLE
On About page, remove .Layout-main grey background color

### ISSUE THREAD

**Issue by akuataya** [Progress-Studies-Forum/ForumMagnum#36]
Let's change to the default white background color for posts.

<img width="1103" alt="Screen Shot 2022-03-12 at 11 36 41 AM" src="https://user-images.githubusercontent.com/11878478/158032464-44ab653a-9fbf-4757-8ab1-228da8b477cc.png">

**Comment by sentalis** [comment]
I noticed this when implementing it, and looked into it _slightly_. This is an odd artifact of _only_ the about page, and _only_ when it's navigated to from the sidebar. I don't know why.

**Comment by sentalis** [comment]
Closed in 223808b7defdf9ca4cb58bbfafbdb82ed9755b30.
